name: pokemon-agent
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.13
  - pip=23.0
  - numpy=1.24.3
  - pip:
    - pyboy==1.4.5
    - pygame==2.5.0
    - pillow==9.5.0
    - gymnasium==0.28.1
    - stable-baselines3==1.8.0
    - torch==2.0.1
    - matplotlib==3.7.2