"""
Pokemon Locations Module - Maps numeric location IDs to named locations.
Enhanced with floor numbers and area specifications to distinguish duplicates.
"""

# Location mapping for Pokémon Red/Blue
# This maps the game's internal map IDs to their actual names
# Enhanced with floor numbers and area specifications
LOCATION_NAMES = {
    0: "Pallet Town",
    1: "Viridian City",
    2: "Pewter City",
    3: "Cerulean City", 
    4: "Lavender Town",
    5: "Vermilion City",
    6: "Celadon City",
    7: "Fuchsia City",
    8: "Cinnabar Island",
    9: "Indigo Plateau",
    10: "Saffron City",
    11: "Route 1",
    12: "Route 2",
    13: "Route 3",
    14: "Route 4",
    15: "Route 5",
    16: "Route 6",
    17: "Route 7",
    18: "Route 8",
    19: "Route 9",
    20: "Route 10",
    21: "Route 11",
    22: "Route 12",
    23: "Route 13",
    24: "Route 14",
    25: "Route 15",
    26: "Route 16",
    27: "Route 17 (Cycling Road)",
    28: "Route 18",
    29: "Route 19",
    30: "Route 20",
    31: "Route 21",
    32: "Route 22",
    33: "Route 23",
    34: "Route 24",
    35: "Route 25",
    36: "Viridian Forest",
    37: "Mt. Moon 1F",
    38: "Rock Tunnel 1F",
    39: "Victory Road 1F",
    40: "Diglett's Cave",
    41: "Viridian Gym",
    42: "Pewter Gym",
    43: "Cerulean Gym",
    44: "Vermilion Gym",
    45: "Celadon Gym",
    46: "Fuchsia Gym",
    47: "Saffron Gym",
    48: "Cinnabar Gym",
    49: "Pokémon Mansion 1F",
    50: "Safari Zone - Main Gate",
    51: "Pokémon Tower 1F",
    52: "S.S. Anne - Entrance",
    53: "Underground Path (Route 5-6)",
    54: "Underground Path (Route 7-8)",
    55: "Pokémon League - Reception Gate",
    56: "Rock Tunnel 2F",
    57: "Silph Co. 1F",
    58: "Pokémon Mansion 2F",
    59: "Safari Zone - East Area",
    60: "Cerulean Cave 1F",
    61: "Power Plant - Entrance",
    62: "Seafoam Islands 1F",
    63: "Pokémon Tower 2F",
    64: "S.S. Anne - Captain's Cabin",
    65: "Mt. Moon B1F",
    66: "Safari Zone - North Area",
    67: "Safari Zone - Main Gate (Interior)",
    68: "Game Corner",
    69: "Rocket Hideout B1F",
    70: "Celadon Department Store 1F",
    71: "Celadon Department Store 2F",
    72: "Celadon Department Store 3F",
    73: "Celadon Department Store 4F",
    74: "Celadon Department Store Roof",
    75: "Celadon Department Store Elevator",
    76: "Celadon Mansion 1F",
    77: "Celadon Mansion 2F",
    78: "Celadon Mansion 3F",
    79: "Celadon Mansion Roof - Left Side",
    80: "Celadon Mansion Roof - Right Side",
    81: "Celadon Mansion Elevator",
    82: "Celadon Pokémon Center",
    83: "Celadon Game Corner Prize Room",
    84: "Fighting Dojo",
    85: "Saffron Gym",
    86: "Saffron House 1",
    87: "Saffron House 2",
    88: "Saffron Mart",
    89: "Silph Co. 2F",
    90: "Saffron Pokémon Center",
    91: "Mr. Psychic's House",
    92: "Route 15 Gate - East Side",
    93: "Route 15 Gate - West Side",
    94: "Route 16 Gate - North Side",
    95: "Route 16 Gate - South Side",
    96: "Route 16 House",
    97: "Route 12 Super Rod House",
    98: "Route 18 Gate - East Side",
    99: "Route 18 Gate - West Side",
    100: "Seafoam Islands B1F",
    101: "Vermilion Trade House",
    102: "Vermilion Fishing Guru",
    103: "Pokémon Fan Club",
    104: "Vermilion Gym",
    105: "Vermilion Pokémon Center",
    106: "Vermilion Mart",
    107: "Vermilion House",
    108: "S.S. Anne - Main Deck",
    109: "S.S. Anne - First Floor Hallway",
    110: "S.S. Anne - Second Floor Hallway",
    111: "Victory Road 2F",
    112: "Route 22 Gate",
    113: "Bill's House",
    114: "Viridian School",
    115: "Viridian Mart",
    116: "Viridian Gym",
    117: "Viridian House",
    118: "Viridian Pokémon Center",
    119: "Route 2 Gate - North Side",
    120: "Route 2 Gate - South Side",
    121: "Route 2 Trade House",
    122: "Route 2 Pokémon Center",
    123: "Oak's Lab",
    124: "Red's House 1F",
    125: "Red's House 2F",
    126: "Blue's House",
    127: "Pewter Museum 1F",
    128: "Pewter Museum 2F",
    129: "Pewter Gym",
    130: "Pewter Mart",
    131: "Pewter House",
    132: "Pewter Pokémon Center",
    133: "Mt. Moon Pokémon Center",
    134: "Cerulean House",
    135: "Cerulean Police Station",
    136: "Cerulean Pokémon Center",
    137: "Cerulean Gym",
    138: "Bike Shop",
    139: "Cerulean Mart",
    140: "Meeting Room",
    141: "Route 5 Gate",
    142: "Underground Path Entrance (Route 5)",
    143: "Daycare",
    144: "Route 6 Gate",
    145: "Underground Path Entrance (Route 6)",
    146: "Route 7 Gate",
    147: "Underground Path Entrance (Route 7)",
    148: "Route 8 Gate",
    149: "Underground Path Entrance (Route 8)",
    150: "Rock Tunnel Pokémon Center",
    151: "Rock Tunnel B1F",
    152: "Power Plant - Main Room",
    153: "Route 11 Gate - East Side",
    154: "Route 11 Gate - West Side",
    155: "Route 12 Gate - North Side",
    156: "Route 12 Gate - South Side",
    157: "Route 12 Fishing House",
    158: "Route 15 Gate - East Side (Interior)",
    159: "Route 15 Gate - West Side (Interior)",
    160: "Route 16 Gate - North Side (Interior)",
    161: "Route 16 Gate - South Side (Interior)",
    162: "Route 16 House (Interior)",
    163: "Route 17 Gate - North Side",
    164: "Route 17 Gate - South Side",
    165: "Route 18 Gate - East Side (Interior)",
    166: "Route 18 Gate - West Side (Interior)",
    167: "Pokémon League - Main Building Entrance",
    168: "Pokémon League - Lorelei's Room",
    169: "Pokémon League - Bruno's Room",
    170: "Pokémon League - Agatha's Room",
    171: "Pokémon League - Lance's Room",
    172: "Pokémon League - Champion's Room",
    173: "Pokémon League - Hall of Fame",
    174: "Underground Path - Main Tunnel",
    175: "Indigo Plateau Lobby",
    176: "Cinnabar Lab - Entrance",
    177: "Cinnabar Lab - Fossil Research Room",
    178: "Cinnabar Lab - Trading Room",
    179: "Cinnabar Gym",
    180: "Cinnabar Pokémon Center",
    181: "Cinnabar Mart",
    182: "Lavender House 1",
    183: "Lavender Mart",
    184: "Lavender Pokémon Center",
    185: "Lavender House 2",
    186: "Pokémon Tower 1F",
    187: "Pokémon Tower 2F",
    188: "Pokémon Tower 3F",
    189: "Pokémon Tower 4F",
    190: "Pokémon Tower 5F",
    191: "Pokémon Tower 6F",
    192: "Pokémon Tower 7F",
    193: "Safari Zone - Center Area",
    194: "Safari Zone - East Area",
    195: "Safari Zone - North Area",
    196: "Safari Zone - West Area",
    197: "Safari Zone - Center Rest House",
    198: "Safari Zone - East Rest House",
    199: "Safari Zone - North Rest House",
    200: "Safari Zone - West Rest House",
    201: "Safari Zone - Secret House (East)",
    202: "Safari Zone - Gate",
    203: "Fuchsia Pokémon Center",
    204: "Fuchsia Mart",
    205: "Fuchsia House 1",
    206: "Warden's House",
    207: "Fuchsia Gym",
    208: "Fuchsia Lab",
    209: "Fuchsia House 2",
    210: "Fuchsia House 3",
    211: "Seafoam Islands B2F",
    212: "Seafoam Islands B3F",
    213: "Seafoam Islands B4F - East Side",
    214: "Seafoam Islands B4F - West Side (Articuno)",
    215: "Vermilion Dock",
    216: "S.S. Anne - Deck 1 Room 1",
    217: "S.S. Anne - Deck 1 Room 2",
    218: "S.S. Anne - Deck 1 Room 3",
    219: "S.S. Anne - Deck 1 Room 4",
    220: "S.S. Anne - Deck 1 Room 5",
    221: "S.S. Anne - Deck 2 Room 1",
    222: "S.S. Anne - Deck 2 Room 2",
    223: "S.S. Anne - Deck 2 Room 3",
    224: "S.S. Anne - Deck 2 Room 4",
    225: "S.S. Anne - Deck 2 Room 5",
    226: "S.S. Anne - Kitchen",
    227: "Diglett's Cave - Main Tunnel",
    228: "Victory Road 2F - North Section",
    229: "Victory Road 3F",
    230: "Victory Road 3F - Exit Section",
    231: "Rocket Hideout B2F",
    232: "Rocket Hideout B3F",
    233: "Rocket Hideout B4F - Giovanni's Room",
    234: "Rocket Hideout - Elevator",
    235: "Silph Co. 3F",
    236: "Silph Co. 4F",
    237: "Silph Co. 5F",
    238: "Silph Co. 6F",
    239: "Silph Co. 7F",
    240: "Silph Co. 8F",
    241: "Silph Co. 9F",
    242: "Silph Co. 10F",
    243: "Silph Co. 11F - President's Office",
    244: "Silph Co. - Elevator",
    245: "Silph Co. - Warp Tile Maze",
    246: "Pokémon Mansion 3F",
    247: "Pokémon Mansion B1F - Northeast",
    248: "Pokémon Mansion B1F - Northwest",
    249: "Pokémon Mansion B1F - Southwest (Lab)",
    250: "Safari Zone - Secret House Area",
    251: "Safari Zone - Hidden Area 1",
    252: "Safari Zone - Hidden Area 2",
    253: "Safari Zone - Hidden Area 3",
    254: "Cerulean Cave 2F",
    255: "Cerulean Cave B1F (Mewtwo)",
    # Specific areas past 255 might vary in implementations
}

# Pokémon species names (all 151 original Pokémon)
POKEMON_NAMES = {
    1: "Bulbasaur",
    2: "Ivysaur",
    3: "Venusaur",
    4: "Charmander",
    5: "Charmeleon",
    6: "Charizard",
    7: "Squirtle",
    8: "Wartortle",
    9: "Blastoise",
    10: "Caterpie",
    11: "Metapod",
    12: "Butterfree",
    13: "Weedle",
    14: "Kakuna",
    15: "Beedrill",
    16: "Pidgey",
    17: "Pidgeotto",
    18: "Pidgeot",
    19: "Rattata",
    20: "Raticate",
    21: "Spearow",
    22: "Fearow",
    23: "Ekans",
    24: "Arbok",
    25: "Pikachu",
    26: "Raichu",
    27: "Sandshrew",
    28: "Sandslash",
    29: "Nidoran♀",
    30: "Nidorina",
    31: "Nidoqueen",
    32: "Nidoran♂",
    33: "Nidorino",
    34: "Nidoking",
    35: "Clefairy",
    36: "Clefable",
    37: "Vulpix",
    38: "Ninetales",
    39: "Jigglypuff",
    40: "Wigglytuff",
    41: "Zubat",
    42: "Golbat",
    43: "Oddish",
    44: "Gloom",
    45: "Vileplume",
    46: "Paras",
    47: "Parasect",
    48: "Venonat",
    49: "Venomoth",
    50: "Diglett",
    51: "Dugtrio",
    52: "Meowth",
    53: "Persian",
    54: "Psyduck",
    55: "Golduck",
    56: "Mankey",
    57: "Primeape",
    58: "Growlithe",
    59: "Arcanine",
    60: "Poliwag",
    61: "Poliwhirl",
    62: "Poliwrath",
    63: "Abra",
    64: "Kadabra",
    65: "Alakazam",
    66: "Machop",
    67: "Machoke",
    68: "Machamp",
    69: "Bellsprout",
    70: "Weepinbell",
    71: "Victreebel",
    72: "Tentacool",
    73: "Tentacruel",
    74: "Geodude",
    75: "Graveler",
    76: "Golem",
    77: "Ponyta",
    78: "Rapidash",
    79: "Slowpoke",
    80: "Slowbro",
    81: "Magnemite",
    82: "Magneton",
    83: "Farfetch'd",
    84: "Doduo",
    85: "Dodrio",
    86: "Seel",
    87: "Dewgong",
    88: "Grimer",
    89: "Muk",
    90: "Shellder",
    91: "Cloyster",
    92: "Gastly",
    93: "Haunter",
    94: "Gengar",
    95: "Onix",
    96: "Drowzee",
    97: "Hypno",
    98: "Krabby",
    99: "Kingler",
    100: "Voltorb",
    101: "Electrode",
    102: "Exeggcute",
    103: "Exeggutor",
    104: "Cubone",
    105: "Marowak",
    106: "Hitmonlee",
    107: "Hitmonchan",
    108: "Lickitung",
    109: "Koffing",
    110: "Weezing",
    111: "Rhyhorn",
    112: "Rhydon",
    113: "Chansey",
    114: "Tangela",
    115: "Kangaskhan",
    116: "Horsea",
    117: "Seadra",
    118: "Goldeen",
    119: "Seaking",
    120: "Staryu",
    121: "Starmie",
    122: "Mr. Mime",
    123: "Scyther",
    124: "Jynx",
    125: "Electabuzz",
    126: "Magmar",
    127: "Pinsir",
    128: "Tauros",
    129: "Magikarp",
    130: "Gyarados",
    131: "Lapras",
    132: "Ditto",
    133: "Eevee",
    134: "Vaporeon",
    135: "Jolteon",
    136: "Flareon",
    137: "Porygon",
    138: "Omanyte",
    139: "Omastar",
    140: "Kabuto",
    141: "Kabutops",
    142: "Aerodactyl",
    143: "Snorlax",
    144: "Articuno",
    145: "Zapdos",
    146: "Moltres",
    147: "Dratini",
    148: "Dragonair",
    149: "Dragonite",
    150: "Mewtwo",
    151: "Mew"
}

# Move names (all moves in Red/Blue)
MOVE_NAMES = {
    1: "Pound",
    2: "Karate Chop",
    3: "Double Slap",
    4: "Comet Punch",
    5: "Mega Punch",
    6: "Pay Day",
    7: "Fire Punch",
    8: "Ice Punch",
    9: "Thunder Punch",
    10: "Scratch",
    11: "Vise Grip",
    12: "Guillotine",
    13: "Razor Wind",
    14: "Swords Dance",
    15: "Cut",
    16: "Gust",
    17: "Wing Attack",
    18: "Whirlwind",
    19: "Fly",
    20: "Bind",
    21: "Slam",
    22: "Vine Whip",
    23: "Stomp",
    24: "Double Kick",
    25: "Mega Kick",
    26: "Jump Kick",
    27: "Rolling Kick",
    28: "Sand Attack",
    29: "Headbutt",
    30: "Horn Attack",
    31: "Fury Attack",
    32: "Horn Drill",
    33: "Tackle",
    34: "Body Slam",
    35: "Wrap",
    36: "Take Down",
    37: "Thrash",
    38: "Double-Edge",
    39: "Tail Whip",
    40: "Poison Sting",
    41: "Twineedle",
    42: "Pin Missile",
    43: "Leer",
    44: "Bite",
    45: "Growl",
    46: "Roar",
    47: "Sing",
    48: "Supersonic",
    49: "Sonic Boom",
    50: "Disable",
    51: "Acid",
    52: "Ember",
    53: "Flamethrower",
    54: "Mist",
    55: "Water Gun",
    56: "Hydro Pump",
    57: "Surf",
    58: "Ice Beam",
    59: "Blizzard",
    60: "Psybeam",
    61: "Bubble Beam",
    62: "Aurora Beam",
    63: "Hyper Beam",
    64: "Peck",
    65: "Drill Peck",
    66: "Submission",
    67: "Low Kick",
    68: "Counter",
    69: "Seismic Toss",
    70: "Strength",
    71: "Absorb",
    72: "Mega Drain",
    73: "Leech Seed",
    74: "Growth",
    75: "Razor Leaf",
    76: "Solar Beam",
    77: "Poison Powder",
    78: "Stun Spore",
    79: "Sleep Powder",
    80: "Petal Dance",
    81: "String Shot",
    82: "Dragon Rage",
    83: "Fire Spin",
    84: "Thunder Shock",
    85: "Thunderbolt",
    86: "Thunder Wave",
    87: "Thunder",
    88: "Rock Throw",
    89: "Earthquake",
    90: "Fissure",
    91: "Dig",
    92: "Toxic",
    93: "Confusion",
    94: "Psychic",
    95: "Hypnosis",
    96: "Meditate",
    97: "Agility",
    98: "Quick Attack",
    99: "Rage",
    100: "Teleport",
    101: "Night Shade",
    102: "Mimic",
    103: "Screech",
    104: "Double Team",
    105: "Recover",
    106: "Harden",
    107: "Minimize",
    108: "Smokescreen",
    109: "Confuse Ray",
    110: "Withdraw",
    111: "Defense Curl",
    112: "Barrier",
    113: "Light Screen",
    114: "Haze",
    115: "Reflect",
    116: "Focus Energy",
    117: "Bide",
    118: "Metronome",
    119: "Mirror Move",
    120: "Self-Destruct",
    121: "Egg Bomb",
    122: "Lick",
    123: "Smog",
    124: "Sludge",
    125: "Bone Club",
    126: "Fire Blast",
    127: "Waterfall",
    128: "Clamp",
    129: "Swift",
    130: "Skull Bash",
    131: "Spike Cannon",
    132: "Constrict",
    133: "Amnesia",
    134: "Kinesis",
    135: "Soft-Boiled",
    136: "High Jump Kick",
    137: "Glare",
    138: "Dream Eater",
    139: "Poison Gas",
    140: "Barrage",
    141: "Leech Life",
    142: "Lovely Kiss",
    143: "Sky Attack",
    144: "Transform",
    145: "Bubble",
    146: "Dizzy Punch",
    147: "Spore",
    148: "Flash",
    149: "Psywave",
    150: "Splash",
    151: "Acid Armor",
    152: "Crabhammer",
    153: "Explosion",
    154: "Fury Swipes",
    155: "Bonemerang",
    156: "Rest",
    157: "Rock Slide",
    158: "Hyper Fang",
    159: "Sharpen",
    160: "Conversion",
    161: "Tri Attack",
    162: "Super Fang",
    163: "Slash",
    164: "Substitute",
    165: "Struggle"
}

# Type names
TYPE_NAMES = {
    0: "Normal",
    1: "Fighting",
    2: "Flying",
    3: "Poison",
    4: "Ground",
    5: "Rock",
    6: "Bug",
    7: "Ghost",
    8: "Fire", 
    9: "Water",
    10: "Grass",
    11: "Electric",
    12: "Psychic",
    13: "Ice",
    14: "Dragon",
    15: "Bird",  # Unused in the final game but appears in the code
    # Types 16-18 are not used but might appear in glitched scenarios
    255: "???"  # For "typeless" or glitched types
}

# Status condition names
STATUS_NAMES = {
    0: "None",
    1: "Asleep",
    2: "Poisoned",
    3: "Burned",
    4: "Frozen",
    5: "Paralyzed",
    8: "Badly Poisoned" # Toxic poison
}

def get_location_name(map_id):
    """
    Get the location name for a map ID.
    
    Args:
        map_id: The numeric map ID
        
    Returns:
        String with location name or "Unknown Location" if ID not found
    """
    return LOCATION_NAMES.get(map_id, f"Unknown Location (ID: {map_id})")

def get_pokemon_name(species_id):
    """
    Get the Pokémon name for a species ID.
    
    Args:
        species_id: The numeric species ID
        
    Returns:
        String with Pokémon name or "Unknown Pokémon" if ID not found
    """
    return POKEMON_NAMES.get(species_id, f"Unknown Pokémon (ID: {species_id})")

def get_move_name(move_id):
    """
    Get the move name for a move ID.
    
    Args:
        move_id: The numeric move ID
        
    Returns:
        String with move name or "Unknown Move" if ID not found
    """
    return MOVE_NAMES.get(move_id, f"Unknown Move (ID: {move_id})")

def get_type_name(type_id):
    """
    Get the type name for a type ID.
    
    Args:
        type_id: The numeric type ID
        
    Returns:
        String with type name or "Unknown Type" if ID not found
    """
    return TYPE_NAMES.get(type_id, f"Unknown Type (ID: {type_id})")

def get_status_name(status_id):
    """
    Get the status condition name for a status ID.
    
    Args:
        status_id: The numeric status ID
        
    Returns:
        String with status name or "Unknown Status" if ID not found
    """
    return STATUS_NAMES.get(status_id, f"Unknown Status (ID: {status_id})")