"""
Pokemon Locations Module - Maps numeric location IDs to named locations.
Enhanced with floor numbers and area specifications to distinguish duplicates.
"""

# Location mapping for Pokémon Red/Blue
# This maps the game's internal map IDs to their actual names
# Enhanced with floor numbers and area specifications
LOCATION_NAMES = {
    0x00: "PALLET_TOWN",
    0x01: "VIRIDIAN_CITY",
    0x02: "PEWTER_CITY",
    0x03: "CERULEAN_CITY",
    0x04: "LAVENDER_TOWN",
    0x05: "VERMILION_CITY",
    0x06: "CELADON_CITY",
    0x07: "FUCHSIA_CITY",
    0x08: "CINNABAR_ISLAND",
    0x09: "INDIGO_PLATEAU",
    0x0A: "SAFFRON_CITY",
    0x0B: "UNUSED_MAP_0B",
    0x0C: "ROUTE_1",
    0x0D: "ROUTE_2",
    0x0E: "ROUTE_3",
    0x0F: "ROUTE_4",
    0x10: "ROUTE_5",
    0x11: "ROUTE_6",
    0x12: "ROUTE_7",
    0x13: "ROUTE_8",
    0x14: "ROUTE_9",
    0x15: "ROUTE_10",
    0x16: "ROUTE_11",
    0x17: "ROUTE_12",
    0x18: "ROUTE_13",
    0x19: "ROUTE_14",
    0x1A: "ROUTE_15",
    0x1B: "ROUTE_16",
    0x1C: "ROUTE_17",
    0x1D: "ROUTE_18",
    0x1E: "ROUTE_19",
    0x1F: "ROUTE_20",
    0x20: "ROUTE_21",
    0x21: "ROUTE_22",
    0x22: "ROUTE_23",
    0x23: "ROUTE_24",
    0x24: "ROUTE_25",
    0x25: "REDS_HOUSE_1F",
    0x26: "REDS_HOUSE_2F",
    0x27: "BLUES_HOUSE",
    0x28: "OAKS_LAB",
    0x29: "VIRIDIAN_POKECENTER",
    0x2A: "VIRIDIAN_MART",
    0x2B: "VIRIDIAN_SCHOOL_HOUSE",
    0x2C: "VIRIDIAN_NICKNAME_HOUSE",
    0x2D: "VIRIDIAN_GYM",
    0x2E: "DIGLETTS_CAVE_ROUTE_2",
    0x2F: "VIRIDIAN_FOREST_NORTH_GATE",
    0x30: "ROUTE_2_TRADE_HOUSE",
    0x31: "ROUTE_2_GATE",
    0x32: "VIRIDIAN_FOREST_SOUTH_GATE",
    0x33: "VIRIDIAN_FOREST",
    0x34: "MUSEUM_1F",
    0x35: "MUSEUM_2F",
    0x36: "PEWTER_GYM",
    0x37: "PEWTER_NIDORAN_HOUSE",
    0x38: "PEWTER_MART",
    0x39: "PEWTER_SPEECH_HOUSE",
    0x3A: "PEWTER_POKECENTER",
    0x3B: "MT_MOON_1F",
    0x3C: "MT_MOON_B1F",
    0x3D: "MT_MOON_B2F",
    0x3E: "CERULEAN_TRASHED_HOUSE",
    0x3F: "CERULEAN_TRADE_HOUSE",
    0x40: "CERULEAN_POKECENTER",
    0x41: "CERULEAN_GYM",
    0x42: "BIKE_SHOP",
    0x43: "CERULEAN_MART",
    0x44: "MT_MOON_POKECENTER",
    0x45: "CERULEAN_TRASHED_HOUSE_COPY",
    0x46: "ROUTE_5_GATE",
    0x47: "UNDERGROUND_PATH_ROUTE_5",
    0x48: "DAYCARE",
    0x49: "ROUTE_6_GATE",
    0x4A: "UNDERGROUND_PATH_ROUTE_6",
    0x4B: "UNDERGROUND_PATH_ROUTE_6_COPY",
    0x4C: "ROUTE_7_GATE",
    0x4D: "UNDERGROUND_PATH_ROUTE_7",
    0x4E: "UNDERGROUND_PATH_ROUTE_7_COPY",
    0x4F: "ROUTE_8_GATE",
    0x50: "UNDERGROUND_PATH_ROUTE_8",
    0x51: "ROCK_TUNNEL_POKECENTER",
    0x52: "ROCK_TUNNEL_1F",
    0x53: "POWER_PLANT",
    0x54: "ROUTE_11_GATE_1F",
    0x55: "DIGLETTS_CAVE_ROUTE_11",
    0x56: "ROUTE_11_GATE_2F",
    0x57: "ROUTE_12_GATE_1F",
    0x58: "BILLS_HOUSE",
    0x59: "VERMILION_POKECENTER",
    0x5A: "POKEMON_FAN_CLUB",
    0x5B: "VERMILION_MART",
    0x5C: "VERMILION_GYM",
    0x5D: "VERMILION_PIDGEY_HOUSE",
    0x5E: "VERMILION_DOCK",
    0x5F: "SS_ANNE_1F",
    0x60: "SS_ANNE_2F",
    0x61: "SS_ANNE_3F",
    0x62: "SS_ANNE_B1F",
    0x63: "SS_ANNE_BOW",
    0x64: "SS_ANNE_KITCHEN",
    0x65: "SS_ANNE_CAPTAINS_ROOM",
    0x66: "SS_ANNE_1F_ROOMS",
    0x67: "SS_ANNE_2F_ROOMS",
    0x68: "SS_ANNE_B1F_ROOMS",
    0x69: "UNUSED_MAP_69",
    0x6A: "UNUSED_MAP_6A",
    0x6B: "UNUSED_MAP_6B",
    0x6C: "VICTORY_ROAD_1F",
    0x6D: "UNUSED_MAP_6D",
    0x6E: "UNUSED_MAP_6E",
    0x6F: "UNUSED_MAP_6F",
    0x70: "UNUSED_MAP_70",
    0x71: "LANCES_ROOM",
    0x72: "UNUSED_MAP_72",
    0x73: "UNUSED_MAP_73",
    0x74: "UNUSED_MAP_74",
    0x75: "UNUSED_MAP_75",
    0x76: "HALL_OF_FAME",
    0x77: "UNDERGROUND_PATH_NORTH_SOUTH",
    0x78: "CHAMPIONS_ROOM",
    0x79: "UNDERGROUND_PATH_WEST_EAST",
    0x7A: "CELADON_MART_1F",
    0x7B: "CELADON_MART_2F",
    0x7C: "CELADON_MART_3F",
    0x7D: "CELADON_MART_4F",
    0x7E: "CELADON_MART_ROOF",
    0x7F: "CELADON_MART_ELEVATOR",
    0x80: "CELADON_MANSION_1F",
    0x81: "CELADON_MANSION_2F",
    0x82: "CELADON_MANSION_3F",
    0x83: "CELADON_MANSION_ROOF",
    0x84: "CELADON_MANSION_ROOF_HOUSE",
    0x85: "CELADON_POKECENTER",
    0x86: "CELADON_GYM",
    0x87: "GAME_CORNER",
    0x88: "CELADON_MART_5F",
    0x89: "GAME_CORNER_PRIZE_ROOM",
    0x8A: "CELADON_DINER",
    0x8B: "CELADON_CHIEF_HOUSE",
    0x8C: "CELADON_HOTEL",
    0x8D: "LAVENDER_POKECENTER",
    0x8E: "POKEMON_TOWER_1F",
    0x8F: "POKEMON_TOWER_2F",
    0x90: "POKEMON_TOWER_3F",
    0x91: "POKEMON_TOWER_4F",
    0x92: "POKEMON_TOWER_5F",
    0x93: "POKEMON_TOWER_6F",
    0x94: "POKEMON_TOWER_7F",
    0x95: "MR_FUJIS_HOUSE",
    0x96: "LAVENDER_MART",
    0x97: "LAVENDER_CUBONE_HOUSE",
    0x98: "FUCHSIA_MART",
    0x99: "FUCHSIA_BILLS_GRANDPAS_HOUSE",
    0x9A: "FUCHSIA_POKECENTER",
    0x9B: "WARDENS_HOUSE",
    0x9C: "SAFARI_ZONE_GATE",
    0x9D: "FUCHSIA_GYM",
    0x9E: "FUCHSIA_MEETING_ROOM",
    0x9F: "SEAFOAM_ISLANDS_B1F",
    0xA0: "SEAFOAM_ISLANDS_B2F",
    0xA1: "SEAFOAM_ISLANDS_B3F",
    0xA2: "SEAFOAM_ISLANDS_B4F",
    0xA3: "VERMILION_OLD_ROD_HOUSE",
    0xA4: "FUCHSIA_GOOD_ROD_HOUSE",
    0xA5: "POKEMON_MANSION_1F",
    0xA6: "CINNABAR_GYM",
    0xA7: "CINNABAR_LAB",
    0xA8: "CINNABAR_LAB_TRADE_ROOM",
    0xA9: "CINNABAR_LAB_METRONOME_ROOM",
    0xAA: "CINNABAR_LAB_FOSSIL_ROOM",
    0xAB: "CINNABAR_POKECENTER",
    0xAC: "CINNABAR_MART",
    0xAD: "CINNABAR_MART_COPY",
    0xAE: "INDIGO_PLATEAU_LOBBY",
    0xAF: "COPYCATS_HOUSE_1F",
    0xB0: "COPYCATS_HOUSE_2F",
    0xB1: "FIGHTING_DOJO",
    0xB2: "SAFFRON_GYM",
    0xB3: "SAFFRON_PIDGEY_HOUSE",
    0xB4: "SAFFRON_MART",
    0xB5: "SILPH_CO_1F",
    0xB6: "SAFFRON_POKECENTER",
    0xB7: "MR_PSYCHICS_HOUSE",
    0xB8: "ROUTE_15_GATE_1F",
    0xB9: "ROUTE_15_GATE_2F",
    0xBA: "ROUTE_16_GATE_1F",
    0xBB: "ROUTE_16_GATE_2F",
    0xBC: "ROUTE_16_FLY_HOUSE",
    0xBD: "ROUTE_12_SUPER_ROD_HOUSE",
    0xBE: "ROUTE_18_GATE_1F",
    0xBF: "ROUTE_18_GATE_2F",
    0xC0: "SEAFOAM_ISLANDS_1F",
    0xC1: "ROUTE_22_GATE",
    0xC2: "VICTORY_ROAD_2F",
    0xC3: "ROUTE_12_GATE_2F",
    0xC4: "VERMILION_TRADE_HOUSE",
    0xC5: "DIGLETTS_CAVE",
    0xC6: "VICTORY_ROAD_3F",
    0xC7: "ROCKET_HIDEOUT_B1F",
    0xC8: "ROCKET_HIDEOUT_B2F",
    0xC9: "ROCKET_HIDEOUT_B3F",
    0xCA: "ROCKET_HIDEOUT_B4F",
    0xCB: "ROCKET_HIDEOUT_ELEVATOR",
    0xCC: "UNUSED_MAP_CC",
    0xCD: "UNUSED_MAP_CD",
    0xCE: "UNUSED_MAP_CE",
    0xCF: "SILPH_CO_2F",
    0xD0: "SILPH_CO_3F",
    0xD1: "SILPH_CO_4F",
    0xD2: "SILPH_CO_5F",
    0xD3: "SILPH_CO_6F",
    0xD4: "SILPH_CO_7F",
    0xD5: "SILPH_CO_8F",
    0xD6: "POKEMON_MANSION_2F",
    0xD7: "POKEMON_MANSION_3F",
    0xD8: "POKEMON_MANSION_B1F",
    0xD9: "SAFARI_ZONE_EAST",
    0xDA: "SAFARI_ZONE_NORTH",
    0xDB: "SAFARI_ZONE_WEST",
    0xDC: "SAFARI_ZONE_CENTER",
    0xDD: "SAFARI_ZONE_CENTER_REST_HOUSE",
    0xDE: "SAFARI_ZONE_SECRET_HOUSE",
    0xDF: "SAFARI_ZONE_WEST_REST_HOUSE",
    0xE0: "SAFARI_ZONE_EAST_REST_HOUSE",
    0xE1: "SAFARI_ZONE_NORTH_REST_HOUSE",
    0xE2: "CERULEAN_CAVE_2F",
    0xE3: "CERULEAN_CAVE_B1F",
    0xE4: "CERULEAN_CAVE_1F",
    0xE5: "NAME_RATERS_HOUSE",
    0xE6: "CERULEAN_BADGE_HOUSE",
    0xE7: "UNUSED_MAP_E7",
    0xE8: "ROCK_TUNNEL_B1F",
    0xE9: "SILPH_CO_9F",
    0xEA: "SILPH_CO_10F",
    0xEB: "SILPH_CO_11F",
    0xEC: "SILPH_CO_ELEVATOR",
    0xED: "UNUSED_MAP_ED",
    0xEE: "UNUSED_MAP_EE",
    0xEF: "TRADE_CENTER",
    0xF0: "COLOSSEUM",
    0xF1: "UNUSED_MAP_F1",
    0xF2: "UNUSED_MAP_F2",
    0xF3: "UNUSED_MAP_F3",
    0xF4: "UNUSED_MAP_F4",
    0xF5: "LORELEIS_ROOM",
    0xF6: "BRUNOS_ROOM",
    0xF7: "AGATHAS_ROOM",
}

# Pokémon species names (all 151 original Pokémon)
POKEMON_NAMES = {
    1: "Bulbasaur",
    2: "Ivysaur",
    3: "Venusaur",
    4: "Charmander",
    5: "Charmeleon",
    6: "Charizard",
    7: "Squirtle",
    8: "Wartortle",
    9: "Blastoise",
    10: "Caterpie",
    11: "Metapod",
    12: "Butterfree",
    13: "Weedle",
    14: "Kakuna",
    15: "Beedrill",
    16: "Pidgey",
    17: "Pidgeotto",
    18: "Pidgeot",
    19: "Rattata",
    20: "Raticate",
    21: "Spearow",
    22: "Fearow",
    23: "Ekans",
    24: "Arbok",
    25: "Pikachu",
    26: "Raichu",
    27: "Sandshrew",
    28: "Sandslash",
    29: "Nidoran♀",
    30: "Nidorina",
    31: "Nidoqueen",
    32: "Nidoran♂",
    33: "Nidorino",
    34: "Nidoking",
    35: "Clefairy",
    36: "Clefable",
    37: "Vulpix",
    38: "Ninetales",
    39: "Jigglypuff",
    40: "Wigglytuff",
    41: "Zubat",
    42: "Golbat",
    43: "Oddish",
    44: "Gloom",
    45: "Vileplume",
    46: "Paras",
    47: "Parasect",
    48: "Venonat",
    49: "Venomoth",
    50: "Diglett",
    51: "Dugtrio",
    52: "Meowth",
    53: "Persian",
    54: "Psyduck",
    55: "Golduck",
    56: "Mankey",
    57: "Primeape",
    58: "Growlithe",
    59: "Arcanine",
    60: "Poliwag",
    61: "Poliwhirl",
    62: "Poliwrath",
    63: "Abra",
    64: "Kadabra",
    65: "Alakazam",
    66: "Machop",
    67: "Machoke",
    68: "Machamp",
    69: "Bellsprout",
    70: "Weepinbell",
    71: "Victreebel",
    72: "Tentacool",
    73: "Tentacruel",
    74: "Geodude",
    75: "Graveler",
    76: "Golem",
    77: "Ponyta",
    78: "Rapidash",
    79: "Slowpoke",
    80: "Slowbro",
    81: "Magnemite",
    82: "Magneton",
    83: "Farfetch'd",
    84: "Doduo",
    85: "Dodrio",
    86: "Seel",
    87: "Dewgong",
    88: "Grimer",
    89: "Muk",
    90: "Shellder",
    91: "Cloyster",
    92: "Gastly",
    93: "Haunter",
    94: "Gengar",
    95: "Onix",
    96: "Drowzee",
    97: "Hypno",
    98: "Krabby",
    99: "Kingler",
    100: "Voltorb",
    101: "Electrode",
    102: "Exeggcute",
    103: "Exeggutor",
    104: "Cubone",
    105: "Marowak",
    106: "Hitmonlee",
    107: "Hitmonchan",
    108: "Lickitung",
    109: "Koffing",
    110: "Weezing",
    111: "Rhyhorn",
    112: "Rhydon",
    113: "Chansey",
    114: "Tangela",
    115: "Kangaskhan",
    116: "Horsea",
    117: "Seadra",
    118: "Goldeen",
    119: "Seaking",
    120: "Staryu",
    121: "Starmie",
    122: "Mr. Mime",
    123: "Scyther",
    124: "Jynx",
    125: "Electabuzz",
    126: "Magmar",
    127: "Pinsir",
    128: "Tauros",
    129: "Magikarp",
    130: "Gyarados",
    131: "Lapras",
    132: "Ditto",
    133: "Eevee",
    134: "Vaporeon",
    135: "Jolteon",
    136: "Flareon",
    137: "Porygon",
    138: "Omanyte",
    139: "Omastar",
    140: "Kabuto",
    141: "Kabutops",
    142: "Aerodactyl",
    143: "Snorlax",
    144: "Articuno",
    145: "Zapdos",
    146: "Moltres",
    147: "Dratini",
    148: "Dragonair",
    149: "Dragonite",
    150: "Mewtwo",
    151: "Mew"
}

# Move names (all moves in Red/Blue)
MOVE_NAMES = {
    1: "Pound",
    2: "Karate Chop",
    3: "Double Slap",
    4: "Comet Punch",
    5: "Mega Punch",
    6: "Pay Day",
    7: "Fire Punch",
    8: "Ice Punch",
    9: "Thunder Punch",
    10: "Scratch",
    11: "Vise Grip",
    12: "Guillotine",
    13: "Razor Wind",
    14: "Swords Dance",
    15: "Cut",
    16: "Gust",
    17: "Wing Attack",
    18: "Whirlwind",
    19: "Fly",
    20: "Bind",
    21: "Slam",
    22: "Vine Whip",
    23: "Stomp",
    24: "Double Kick",
    25: "Mega Kick",
    26: "Jump Kick",
    27: "Rolling Kick",
    28: "Sand Attack",
    29: "Headbutt",
    30: "Horn Attack",
    31: "Fury Attack",
    32: "Horn Drill",
    33: "Tackle",
    34: "Body Slam",
    35: "Wrap",
    36: "Take Down",
    37: "Thrash",
    38: "Double-Edge",
    39: "Tail Whip",
    40: "Poison Sting",
    41: "Twineedle",
    42: "Pin Missile",
    43: "Leer",
    44: "Bite",
    45: "Growl",
    46: "Roar",
    47: "Sing",
    48: "Supersonic",
    49: "Sonic Boom",
    50: "Disable",
    51: "Acid",
    52: "Ember",
    53: "Flamethrower",
    54: "Mist",
    55: "Water Gun",
    56: "Hydro Pump",
    57: "Surf",
    58: "Ice Beam",
    59: "Blizzard",
    60: "Psybeam",
    61: "Bubble Beam",
    62: "Aurora Beam",
    63: "Hyper Beam",
    64: "Peck",
    65: "Drill Peck",
    66: "Submission",
    67: "Low Kick",
    68: "Counter",
    69: "Seismic Toss",
    70: "Strength",
    71: "Absorb",
    72: "Mega Drain",
    73: "Leech Seed",
    74: "Growth",
    75: "Razor Leaf",
    76: "Solar Beam",
    77: "Poison Powder",
    78: "Stun Spore",
    79: "Sleep Powder",
    80: "Petal Dance",
    81: "String Shot",
    82: "Dragon Rage",
    83: "Fire Spin",
    84: "Thunder Shock",
    85: "Thunderbolt",
    86: "Thunder Wave",
    87: "Thunder",
    88: "Rock Throw",
    89: "Earthquake",
    90: "Fissure",
    91: "Dig",
    92: "Toxic",
    93: "Confusion",
    94: "Psychic",
    95: "Hypnosis",
    96: "Meditate",
    97: "Agility",
    98: "Quick Attack",
    99: "Rage",
    100: "Teleport",
    101: "Night Shade",
    102: "Mimic",
    103: "Screech",
    104: "Double Team",
    105: "Recover",
    106: "Harden",
    107: "Minimize",
    108: "Smokescreen",
    109: "Confuse Ray",
    110: "Withdraw",
    111: "Defense Curl",
    112: "Barrier",
    113: "Light Screen",
    114: "Haze",
    115: "Reflect",
    116: "Focus Energy",
    117: "Bide",
    118: "Metronome",
    119: "Mirror Move",
    120: "Self-Destruct",
    121: "Egg Bomb",
    122: "Lick",
    123: "Smog",
    124: "Sludge",
    125: "Bone Club",
    126: "Fire Blast",
    127: "Waterfall",
    128: "Clamp",
    129: "Swift",
    130: "Skull Bash",
    131: "Spike Cannon",
    132: "Constrict",
    133: "Amnesia",
    134: "Kinesis",
    135: "Soft-Boiled",
    136: "High Jump Kick",
    137: "Glare",
    138: "Dream Eater",
    139: "Poison Gas",
    140: "Barrage",
    141: "Leech Life",
    142: "Lovely Kiss",
    143: "Sky Attack",
    144: "Transform",
    145: "Bubble",
    146: "Dizzy Punch",
    147: "Spore",
    148: "Flash",
    149: "Psywave",
    150: "Splash",
    151: "Acid Armor",
    152: "Crabhammer",
    153: "Explosion",
    154: "Fury Swipes",
    155: "Bonemerang",
    156: "Rest",
    157: "Rock Slide",
    158: "Hyper Fang",
    159: "Sharpen",
    160: "Conversion",
    161: "Tri Attack",
    162: "Super Fang",
    163: "Slash",
    164: "Substitute",
    165: "Struggle"
}

# Type names
TYPE_NAMES = {
    0: "Normal",
    1: "Fighting",
    2: "Flying",
    3: "Poison",
    4: "Ground",
    5: "Rock",
    6: "Bug",
    7: "Ghost",
    8: "Fire", 
    9: "Water",
    10: "Grass",
    11: "Electric",
    12: "Psychic",
    13: "Ice",
    14: "Dragon",
    15: "Bird",  # Unused in the final game but appears in the code
    # Types 16-18 are not used but might appear in glitched scenarios
    255: "???"  # For "typeless" or glitched types
}

# Status condition names
STATUS_NAMES = {
    0: "None",
    1: "Asleep",
    2: "Poisoned",
    3: "Burned",
    4: "Frozen",
    5: "Paralyzed",
    8: "Badly Poisoned" # Toxic poison
}

def get_location_name(map_id):
    """
    Get the location name for a map ID.
    
    Args:
        map_id: The numeric map ID
        
    Returns:
        String with location name or "Unknown Location" if ID not found
    """
    return LOCATION_NAMES.get(map_id, f"Unknown Location (ID: {map_id})")

def get_pokemon_name(species_id):
    """
    Get the Pokémon name for a species ID.
    
    Args:
        species_id: The numeric species ID
        
    Returns:
        String with Pokémon name or "Unknown Pokémon" if ID not found
    """
    return POKEMON_NAMES.get(species_id, f"Unknown Pokémon (ID: {species_id})")

def get_move_name(move_id):
    """
    Get the move name for a move ID.
    
    Args:
        move_id: The numeric move ID
        
    Returns:
        String with move name or "Unknown Move" if ID not found
    """
    return MOVE_NAMES.get(move_id, f"Unknown Move (ID: {move_id})")

def get_type_name(type_id):
    """
    Get the type name for a type ID.
    
    Args:
        type_id: The numeric type ID
        
    Returns:
        String with type name or "Unknown Type" if ID not found
    """
    return TYPE_NAMES.get(type_id, f"Unknown Type (ID: {type_id})")

def get_status_name(status_id):
    """
    Get the status condition name for a status ID.
    
    Args:
        status_id: The numeric status ID
        
    Returns:
        String with status name or "Unknown Status" if ID not found
    """
    return STATUS_NAMES.get(status_id, f"Unknown Status (ID: {status_id})")